/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e5e1e6",
        "on-error": "#fff7f7",
        "secondary-fixed-dim": "#d7d3d8",
        "on-surface-variant": "#2f619a",
        "surface": "#f8f9ff",
        "on-secondary-container": "#525155",
        "inverse-surface": "#010f21",
        "on-secondary": "#fcf8fc",
        "secondary-dim": "#545256",
        "inverse-primary": "#a19ff9",
        "on-error-container": "#782232",
        "on-primary-container": "#4a479b",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#c5dbff",
        "surface-container-highest": "#d3e3ff",
        "on-primary": "#faf6ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#4b526c",
        "secondary-fixed": "#e5e1e6",
        "error-container": "#ff8b9a",
        "outline-variant": "#87b4f3",
        "on-background": "#003360",
        "on-surface": "#003360",
        "on-primary-fixed-variant": "#5352a5",
        "primary": "#5654a8",
        "surface-container": "#e6eeff",
        "tertiary-container": "#d2d9f8",
        "error": "#9e3f4e",
        "primary-dim": "#4a489b",
        "on-primary-fixed": "#373487",
        "on-secondary-fixed-variant": "#5c5b5f",
        "tertiary-fixed": "#d2d9f8",
        "secondary": "#605e62",
        "on-tertiary-fixed": "#323951",
        "surface-variant": "#d3e3ff",
        "surface-container-high": "#dde9ff",
        "tertiary-fixed-dim": "#c4cbe9",
        "inverse-on-surface": "#8f9eb5",
        "primary-container": "#e2dfff",
        "primary-fixed-dim": "#d2d0ff",
        "on-tertiary": "#f9f8ff",
        "tertiary": "#575e78",
        "on-tertiary-container": "#444c65",
        "background": "#f8f9ff",
        "on-secondary-fixed": "#403f43",
        "error-dim": "#4f0116",
        "outline": "#4e7db7",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#5654a8",
        "on-tertiary-fixed-variant": "#4e556f",
        "surface-bright": "#f8f9ff"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
